<!-- CONTENT HEADER -->

<div class="content_header">
    <img class="bg1">
    <img class="rellax bg2" data-rellax-speed="-5">
    <img class="rellax bg3" data-rellax-speed="-8">
    <h1>écrivain,<br>acteur</h1>
    <p>Découvrez mes nouveaux romans en ligne </p>
</div>
<div class="rs" >
    <i class="fab fa-twitter-square"></i>
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-instagram"></i>
    <i class="fab fa-linkedin"></i>
</div>

<!-- LISTE DES ROMANS -->
 
<div class="list_roman">
    <?php foreach($romans as $roman): ?>
    <div id="list">
        <h1>0<?= $roman['id'] ?></h1>
        <h2><?= $roman['title'] ?></h2>
        <br>
        <i class="fas fa-angle-up"></i>
        <i class="fas fa-angle-down"></i>
        <p><?= $roman['resum'] ?><br><br>
        <a href="/jean-forteroche/chapitres"><i class="fas fa-long-arrow-alt-right"></i> Lire le roman</a></p>
    </div>
    <?php endforeach; ?>
    <div id="content_list">
        <ul>
            <li><img src="public/assets/img/roman_1.jpg" alt=""></li>
        </ul>
        <div id="selct_start"></div>
        <div id="selct_end"></div>
    </div>
</div>

<!-- BOUTIQUE -->

<div class="shop">
    <ul>
        <li><img src="public/assets/img/book1.jpg" title="©Julia Assad">
            <p>“L’écho de ton souvenir”<br><span id="price">10.90€</span></p><button>Acheter <i
                    class="fas fa-shopping-cart"></i></button>
        </li>
        <li><img src="public/assets/img/book2.jpg" title="©Julia Assad">
            <p>“L’enfant qui venait des étoiles”<br><span id="price">11.90€</span></p><button>Acheter <i
                    class="fas fa-shopping-cart"></i></button>
        </li>
        <li><img src="public/assets/img/book3.jpg" title="©Julia Assad">
            <p>“On se reverra”<br><span id="price">10.90€</span></p><button>Acheter <i
                    class="fas fa-shopping-cart"></i></button>
        </li>
    </ul>
</div>