<div class="main_admin">
    <h1>Dashboard</h1>
    <p>Bienvenue, Admin</p>

    <div class="content_rs">
        <div id="tweet">
            <i class="fab fa-twitter"></i>
            <p>Twitter <br><span id="number_rs">&nbsp;1507</span>
            </p>
        </div>
        <div id="fb">
            <i class="fab fa-facebook-f"></i>
            <p>Facebook <br><span id="number_rs">&nbsp;2707</span></p>
        </div>
        <div id="insta">
            <i class="fab fa-instagram-square"></i>
            <p>Instagram <br><span id="number_rs">&nbsp;1202</span></p>
        </div>
        <div id="in">
            <i class="fab fa-linkedin"></i>
            <p>Linkedin <br><span id="number_rs"></span></p>
        </div>
    </div>

    <div class="comment_report">
        <h2>Commentaires indésirables&nbsp;&nbsp;<span id="badge_comment">2</span></h2>
        <div class="slot_report">
            <i class="fas fa-link" id="link_del"><i class="far fa-trash-alt"></i></i>
            <i class="fas fa-user-slash" id="user_report"></i>
            <h3>User Name <br><span id="date_report">21/02/2020 à 22h50</span></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci, libero tortor sit netus. Cras mauris ut consectetur sodales venenatis. Id id scelerisque sit scelerisque hendrerit odio. Et sed sed libero ac. Varius eget nunc euismod vulputate non interdum ut id. Vitae lacus orci urna mi. Vitae pellentesque vulputate diam, iaculis massa. Scelerisque aliquam ac purus adipiscing. Commodo turpis mauris enim neque.</p>
        </div>
        <div class="slot_report">
            <i class="fas fa-link" id="link_del"><i class="far fa-trash-alt"></i></i>
            <i class="fas fa-user-slash" id="user_report"></i>
            <h3>User Name <br><span id="date_report">21/02/2020 à 22h50</span></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci, libero tortor sit netus. Cras mauris ut consectetur sodales venenatis. Id id scelerisque sit scelerisque hendrerit odio. Et sed sed libero ac. Varius eget nunc euismod vulputate non interdum ut id. Vitae lacus orci urna mi. Vitae pellentesque vulputate diam, iaculis massa. Scelerisque aliquam ac purus adipiscing. Commodo turpis mauris enim neque.</p>
        </div>
        <div class="slot_report">
            <i class="fas fa-link" id="link_del"><i class="far fa-trash-alt"></i></i>
            <i class="fas fa-user-slash" id="user_report"></i>
            <h3>User Name <br><span id="date_report">21/02/2020 à 22h50</span></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci, libero tortor sit netus. Cras mauris ut consectetur sodales venenatis. Id id scelerisque sit scelerisque hendrerit odio. Et sed sed libero ac. Varius eget nunc euismod vulputate non interdum ut id. Vitae lacus orci urna mi. Vitae pellentesque vulputate diam, iaculis massa. Scelerisque aliquam ac purus adipiscing. Commodo turpis mauris enim neque.</p>
        </div>
        <div class="slot_report">
            <i class="fas fa-link" id="link_del"><i class="far fa-trash-alt"></i></i>
            <i class="fas fa-user-slash" id="user_report"></i>
            <h3>User Name <br><span id="date_report">21/02/2020 à 22h50</span></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci, libero tortor sit netus. Cras mauris ut consectetur sodales venenatis. Id id scelerisque sit scelerisque hendrerit odio. Et sed sed libero ac. Varius eget nunc euismod vulputate non interdum ut id. Vitae lacus orci urna mi. Vitae pellentesque vulputate diam, iaculis massa. Scelerisque aliquam ac purus adipiscing. Commodo turpis mauris enim neque.</p>
        </div>
        <div class="slot_report">
            <i class="fas fa-link" id="link_del"><i class="far fa-trash-alt"></i></i>
            <i class="fas fa-user-slash" id="user_report"></i>
            <h3>User Name <br><span id="date_report">21/02/2020 à 22h50</span></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci, libero tortor sit netus. Cras mauris ut consectetur sodales venenatis. Id id scelerisque sit scelerisque hendrerit odio. Et sed sed libero ac. Varius eget nunc euismod vulputate non interdum ut id. Vitae lacus orci urna mi. Vitae pellentesque vulputate diam, iaculis massa. Scelerisque aliquam ac purus adipiscing. Commodo turpis mauris enim neque.</p>
        </div>
        <p id="see_more">Voir plus <i class="fas fa-chevron-down"></i></p>
    </div>
</div>