<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jean Forteroche</title>
    <link rel="icon" href="/jean-forteroche/public/assets/img/favicon.png">
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/jean-forteroche/public/assets/css/style.css">
</head>

<body>
    <!-- HEADER -->

    <header>
        <i class="fas fa-bars"></i>
        <a href="/jean-forteroche"><img src="/jean-forteroche/public/assets/img/logo.png" alt="logo"></a>
    </header>


    <?= $content ?>


    <!-- FOOTER -->

    <footer>
        <img src="/jean-forteroche/public/assets/img/logo_footer.png" alt="logo_footer">
        <ul>
            <li><span>Admin</span></li>
            <li><a href="/jean-forteroche/login">Se connecter</a></li>
        </ul>
        <ul>
            <li><span>Réseaux sociaux</span></li>
            <li>Facebook</li>
            <li>Twitter</li>
        </ul>
        <ul>
            <li><span>Plan du site</span></li>
            <li>Accueil</li>
            <li>Contact</li>
        </ul>
    </footer>
    <!-- JS -->
    <script src="/jean-forteroche/public/assets/js/slidRoman.js"></script>
    <script src="/jean-forteroche/public/assets/js/dist/SwupOverlayTheme.js"></script>
    <script src="https://unpkg.com/swup@latest/dist/swup.min.js"></script>  
    <script src="https://kit.fontawesome.com/a5f0c7cf2a.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js"></script>
    <script src="/jean-forteroche/public/assets/js/rellax.js"></script>
    <script src="/jean-forteroche/public/assets/js/app.js"></script>

</body>

</html>